### ISSUE TITLE
Unit test AvailabilityResolver

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL-discovery/discovery-api#31]
The AvailabilityResolver is well setup to be unit tested.

We can use something like [sepia](https://github.com/linkedin/sepia) (VCR for node) to record and stub
ElasticSearch & SCSB responses. This will allow us to write lots of expectations about how we expect availability to be munged refactor the implementation with confidence.

**Comment by jobinthomasnypl** [comment]
@nodanaonlyzuul is it okay to close this issue?

**Comment by nodanaonlyzuul** [comment]
DOITDOITDOIT

Phone. Brevity. Typos.

**Comment by jobinthomasnypl** [comment]
Done :)
