### ISSUE TITLE
Availability integration should change `requestable` property too

### ISSUE THREAD

**Issue by nonword** [NYPL-discovery/discovery-api#42]
Related to https://github.com/NYPL-discovery/discovery-api/issues/41 , when intercepting ES response, in addition to modifying the `status` property, we should modify the `requestable` property to `true` if it's available. 

Background: `requestable` is a convenience property provided to API consumers that means: This item can be requested. For some items it's computed against 4 property values. For recap items it's computed as essentially just `status.id === 'a'`

cc @jobinthomasnypl @nodanaonlyzuul

**Comment by nodanaonlyzuul** [comment]
For posterity...

There's a PR for this https://github.com/NYPL-discovery/discovery-api/pull/43/files.
And as said in that PR's ongoing conversation - we I'm not sure how / where requestability is being computed for non-recap NYPL items.

**Comment by nodanaonlyzuul** [comment]
This can be closed.
As of writing the code has been deployed that has the most recent thinking.
