### ISSUE TITLE
Add more logic to 'requestable` property

### ISSUE THREAD

**Issue by nodanaonlyzuul** [NYPL-discovery/discovery-api#48]
Hello!

### So Far So Good

In https://github.com/NYPL-discovery/discovery-api/pull/43 we got the infrastructure to set requestability for an item. Right now we have simple logic:

```none
if (item is in the recap facility)
  Being available means it is requstable
else
  //this is a Sierra item...
  //the existing Discovery infrastructure will keep a 'requestable'
  // property in sync in our index
end
```

### But there's a little work to do

We need a little more nuance for **NYPL-owned items at the ReCAP facility**. (that's the top of that if/else above).

@katesweeney has put together a ticket in [DIS-56](https://jira.nypl.org:8443/browse/DIS-56) that discusses additional logic for NYPL-owned items at the ReCAP facility's `requestable` status.

My knee jerk reaction is that:

1.  This app is the final arbiter of setting `requestable` to the front end.
The front end should take this app's word and not build business logic to parse
this API's response.

2.  This app will probably draw on data based on the CSV / JSON files expertly crafted by
@saverkamp and @katesweeney's python scripts. And implement the requestable logic based on that info. 

### Next Steps / Impediments

So what's next?
Is the next step to put those scripts / csvs / json files in their own repository?
Then have a chat with @katesweeney to discuss questions about [DIS-56](https://jira.nypl.org:8443/browse/DIS-56).

CCing: @katesweeney / @jobinthomasnypl / @kfriedman / @natalietsch / @saverkamp / @nonword / @RobKelley

**Comment by saverkamp** [comment]
I created a new repository for the scripts/csv/json at https://github.com/NYPL/nypl-core. (They will go into /vocabularies)

I can move my python scripts and the csv/json files over on Monday.

**Comment by nodanaonlyzuul** [comment]
Sounds good @saverkamp.
Let me know if you want any help whatsoever

**Comment by nodanaonlyzuul** [comment]
Closing this issue as of https://github.com/NYPL-discovery/discovery-api/pull/61
