### ISSUE TITLE
Intermittent "Invalid patronId" error on deliveryLocationsByBarcode endpoint

### ISSUE THREAD

**Issue by kfriedman** [NYPL-discovery/discovery-api#74]
I know this has been discussed in-person but documenting/reporting it here:

It appears we're intermittently seeing "Invalid patronId" errors on the `deliveryLocationsByBarcode` endpoint.

Restarting the app fixes the issue so it looks like it might be a OAuth token caching issue?

**Comment by nonword** [comment]
For review by any interested https://github.com/NYPL-discovery/node-nypl-data-api-client/pull/1

**Comment by nodanaonlyzuul** [comment]
Fixed via https://github.com/NYPL-discovery/node-nypl-data-api-client/pull/1
